apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-cp4i-ace
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/cp4i-ace/namespace
    repoURL: https://github.com/cloud-native-toolkit-gj-ka/gitops-cp-app-demoapp
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
